### ISSUE TITLE
Can't open OPL files on a Psion 5

### ISSUE THREAD

**Issue by BuildTheRobots** [mlk/aoc#1]
Mad respect - you're the first person I've seen attempt AoC on a Psion. Have been thinking of doing similar but had no idea where to start - hence how I've found your repo.

I've got a stock 5 with a CF card and have copied your OPL files onto it, however they aren't recognised as either OPL scripts or executables - I was wondering if you could advise or had any memories/hints from when you were working on it?

Greatest of thanks :)

**Comment by mlk** [comment]
I think I'll need to export them as text. I've done the first couple. From memory Psion did something odd around working out file types. 

My recommendation would be to get the book Programming for Psion Computers by Leigh Edwards. I spent a lot of time flicking through that while working on the Psion solutions.  Good luck.

**Comment by mlk** [comment]
Pushed text versions of each file. You should be able to import them into the OPL.

**Comment by BuildTheRobots** [comment]
Oh wow!
I really can't thank you enough - was really hoping to save you from having to convert them all, but I really couldn't find any way of getting my Psion to read them in their binary (?) form.
Massive thanks - and for the recommendation. Hope you're enjoying this years AoC

**Comment by BuildTheRobots** [comment]
Just a quick update (as I accidentally bought another Psion a couple of nights ago):
You binary OPL files import and open fine on a Psion 5MX, but aren't editable on the standard 5. 

I can only assume they must have changed the file format between the two versions. Furthermore, as I can't seem to translate them into something readable with PsiWin, I can only assume this naffed a number of people off at the time.

In case anyone finds this in the future, 5 vs 5mx execution times are significantly different.
```
2015/01 pt1:
5  : 25 seconds
5mx: 12 seconds
```

Thanks again :)
